export enum AgendaEvents {
  REJECT_NOT_PAID_ORDER = 'REJECT_NOT_PAID_ORDER',
  COMPUTE_SUB_CATEGORIES_PRODUCTS_AMOUNT = 'COMPUTE_SUB_CATEGORIES_PRODUCTS_AMOUNT',
  REMOVE_VALIDATION_CODE = 'REMOVE_VALIDATION_CODE',
  REMOVE_ORDER_IN_CONSTRUCTION = 'REMOVE_ORDER_IN_CONSTRUCTION',
  TRAINING_NLP_BUSINESS = 'TRAINING_NLP_BUSINESS',
  LOG_OUT_FOR_INACTIVITY = 'LOG_OUT_FOR_INACTIVITY'
}
